### PR TITLE
Switch to `cht-nootils`

### PR DESCRIPTION
**Pull request by dianabarsan**
medic/cht-core#6586

### CODE REVIEW

**Comment by dianabarsan** [comment]
hey @garethbowen . Just checking if this enough for the renaming code-wise. Should I also bump the version? 
This will be followed by publishing on NPM and actually renaming the repo.

**Comment by garethbowen** [comment]
I think it'd be worth bumping the version so there's no confusion.

**Comment by dianabarsan** [comment]
I bumped the minor. Please review, @garethbowen . Thanks a lot!

**Review by garethbowen — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
